# Generated by Django 4.1.7 on 2023-05-16 13:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('received_points', models.TextField()),
                ('closest_points', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
